### ISSUE TITLE
Crashing inputs discovered by AFL

### ISSUE THREAD

**Issue by mmcco** [ender672/farbfeld-resize#1]
I don't understand the code and I don't think I easily could, so I'll leave the debugging to you.

Thanks for your time,
Mike

![id 000000 src 000031 op havoc rep 4](https://user-images.githubusercontent.com/1668979/33159974-ce2837f2-cfd5-11e7-9866-7df079c77a73.png)
![id 000007 sig 11 src 000031 op int32 pos 11 val be 1](https://user-images.githubusercontent.com/1668979/33159975-ce3e22ce-cfd5-11e7-84d2-16136dcce25d.png)
![id 000006 sig 08 src 000029 op flip1 pos 8](https://user-images.githubusercontent.com/1668979/33159976-ce5105e2-cfd5-11e7-8c4a-26541143dff9.png)
![id 000005 sig 08 src 000007 op int8 pos 15 val 0](https://user-images.githubusercontent.com/1668979/33159977-ce63d5fa-cfd5-11e7-9850-f49427e0e815.png)
![id 000004 sig 08 src 000002 op havoc rep 32](https://user-images.githubusercontent.com/1668979/33159978-ce7f4646-cfd5-11e7-9229-b4a34a4bf294.png)
![id 000003 sig 11 src 000002 op int32 pos 8 val 16](https://user-images.githubusercontent.com/1668979/33159979-cea17b94-cfd5-11e7-9ced-3e8886b40255.png)
![id 000002 sig 08 src 000002 op flip1 pos 12](https://user-images.githubusercontent.com/1668979/33159980-ceba7432-cfd5-11e7-9266-cc4e56e2c7ce.png)
![id 000001 sig 11 src 000002 op flip1 pos 8](https://user-images.githubusercontent.com/1668979/33159981-cedef334-cfd5-11e7-933b-078a082e4934.png)
![id 000000 sig 08 src 000002 op flip1 pos 8](https://user-images.githubusercontent.com/1668979/33159982-cef45d5a-cfd5-11e7-94b4-0e73cd7a1ef9.png)

[README.txt](https://github.com/ender672/farbfeld-resize/files/1498086/README.txt)

**Comment by ender672** [comment]
Thanks for doing this! There were overflow issues when calculating malloc sizes on huge input image dimensions. I suspect that an input image with zero height/width was problematic too.

Should be fixed now. Can you confirm?

**Comment by mmcco** [comment]
I've been fuzzing for 22.8 million execs and haven't found anything. Absence of evidence isn't evidence of absence, but it definitely seems like you fixed these bugs.
